export default interface Settings {
    input           : string
    output          : string
    log             : string
    seed            : string
    digimon         : string
    digiDropItem    : string
    digiDropRate    : string
    digiMatchValue  : string
    techs           : string
    techMode        : string
    techPower       : string
    techCost        : string
    techAccuracy    : string
    techEffect      : string
    techEffChance   : string
    starter         : string
    starterWeakest  : string
    recruitment     : string
    chests          : string
    chestsEvo       : string
    tokomon         : string
    tokomonConsume  : string
    techgifts       : string
    spawn           : string
    spawnFoodOnly   : string
    spawnItemCutoff : string
    evo             : string
    evoReqs         : string
    evoSpecial      : string
    evoObtainAll    : string
    patchEvoStats   : string
    patchDropQuest  : string
    patchFixBrain   : string
    patchFixGiromon : string
    patchTechLearn  : string
    patchSpawnRate  : string
    patchWoah       : string
    patchGabu       : string
}
